---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    - Percona-Server-server-57
    - MySQL-python

- name: Copy MySQL configs
  template:
    src: "{{ item.src }}"
    dest: "{{ mysql_config_dir }}/{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: 01-base.cnf.j2, dest: 01-base.cnf }
    - { src: 02-max-connections.cnf.j2, dest: 02-max-connections.cnf }
    - { src: 03-performance.cnf.j2, dest: 03-performance.cnf }
    - { src: 04-slow-query.cnf.j2, dest: 04-slow-query.cnf }
    - { src: 05-binlog.cnf.j2, dest: 05-binlog.cnf }

- name: start mysqld
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Get temporary generated root password
  shell: grep 'root@localhost:' /var/log/mysqld.log | awk '{print $11}'
  register: temporary_root_password
  args:
    creates: "{{ mysql_root_mycnf_path }}"

- name: Update root password
  shell: >
    mysql -uroot -p'{{ temporary_root_password.stdout }}' --connect-expired-password
    -e "ALTER USER USER() IDENTIFIED BY '{{ mysql_root_password }}';"
  args:
    creates: "{{ mysql_root_mycnf_path }}"

- name: Copy root my.cnf file
  template:
    src: my.cnf.j2
    dest: "{{ mysql_root_mycnf_path }}"
    owner: root
    group: root
    mode: '0600'

- name: Create database
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present

- name: restore database
  mysql_db:
    state: import
    name: "{{ mysql_db_name }}"
    target: "{{ mysql_db_dump_path }}"

- name: Create user for replication
  mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_user_password }}"
    priv: "{{ mysql_replication_user_privilege }}"
    host: '%'
    state: present

- name: Create database dump
  mysql_db:
    state: dump
    name: all
    ignore_tables: "{{ mysql_replication_ignored_tables }}"
    target: "{{ mysql_replication_dump_path }}"

- name: Pull dump file from master to host
  fetch:
    src: "{{ mysql_replication_dump_path }}"
    dest: "{{ mysql_replication_dump_path }}"
    flat: yes
